### PR TITLE
Fix icons based on new Nerd Fonts version

### PR DESCRIPTION
**Pull request by fadihania**
Replace the old Material Design Icons, according to Nerd Fonts in latest major release all old mdi icons were remove from the font

## Description
According to Nerd Fonts, "The old Material Design Icon codepoints are finally dropped"
https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

So, the new icons were added and replaced the themes icons. In addition to, introducing new icons for Angular and Karma

## Motivation and Context
The Terminal Icons now broken and not showing all icons as before

## How Has This Been Tested?
Locally on my machine by creating updated files and test icons in terminal, including Show-TerminalIconsTheme command

## Screenshots (if appropriate):
image
image
image

After updates
image

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ryanspletzer** [comment]
This may be a duplicate of #104.

**Comment by devblackops** [comment]
Thanks @fadihania. This looks like a dupe of #104. I merged that one and should take care of the v3 NF issue.

**Comment by fadihania** [comment]
> Thanks @fadihania. This looks like a dupe of #104. I merged that one and should take care of the v3 NF issue.

That's good for the update to the new Nerd Fonts version, but there's another part about missing icons, colors or those using old logos. These are not part of the #104

Shall I create a separate PR for those updates??

**Comment by ryanspletzer** [comment]
@fadihania I would say yes.

**Comment by fadihania** [comment]
A new one already created, please have a look #108

**Pull request closed without merging**
